_target_: src.models.dlib_module.DlibLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.01
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.my_net.ConvNet
  block:
    _target_: src.models.components.my_net.conv_block
    _partial_: true
  layers: [1, 1, 1, 1]
  input_size: [3, 224, 224]
  output_size: [68, 2]
