_target_: src.models.dlib_module.DlibLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.my_resnet.ResNet
  block:
    _target_: src.models.components.my_resnet.Residual_Block
    _partial_: true
  layers: [2, 2, 2, 2]
  input_size: [3, 224, 224]
  output_size: [68, 2]
